### ISSUE TITLE
ClassNotFoundException: javassist.ClassPath

### ISSUE THREAD

**Issue by monkeycraps** [Percy0601/boot-dubbo#4]
为什么 api 的 pom 里要把 javassist exclude 掉，启动 boot-dubbo-simple 过程报错 

`````` java
Caused by: java.lang.ClassNotFoundException: javassist.ClassPath
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 35 common frames omitted
```java
``````

**Comment by monkeycraps** [comment]
应该是 idea ide 的兼容问题，我本地 install 了 dubbox 后，需要重启 ide 才生效，这种情况下，那个 exclution 不影响

**Comment by Percy0601** [comment]
mvn clean install -U -Dmaven.test.skip=true
你试试强制更新

**Comment by leiguorui** [comment]
可能缺少依赖

```
		<dependency>
			<groupId>javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.12.1.GA</version>
		</dependency>
```
