### ISSUE TITLE
Caused by: java.lang.IllegalStateException: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!

### ISSUE THREAD

**Issue by kk580kk** [Percy0601/boot-dubbo#5]
我clone了代码，然后尝试用spring-boot启动simple包，发现报错如下。猜测可能是spring版本和dubbo版本有一点冲突吧。

`Caused by: java.lang.ExceptionInInitializerError: null
    at com.alibaba.dubbo.config.spring.AnnotationBean.postProcessAfterInitialization(AnnotationBean.java:145)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
    ... 18 common frames omitted
Caused by: java.lang.IllegalStateException: fail to create adaptive instance: java.lang.IllegalStateException: Can not create adaptive extenstion interface com.alibaba.dubbo.common.extension.ExtensionFactory, cause: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
    at com.alibaba.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:459)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:129)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:121)
    at com.alibaba.dubbo.config.ServiceConfig.<clinit>(ServiceConfig.java:62)
    ... 22 common frames omitted
Caused by: java.lang.IllegalStateException: Can not create adaptive extenstion interface com.alibaba.dubbo.common.extension.ExtensionFactory, cause: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
    at com.alibaba.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:723)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:455)
    ... 25 common frames omitted
Caused by: java.lang.IllegalStateException: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
    at com.alibaba.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClassCode(ExtensionLoader.java:754)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:736)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:732)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:721)
    ... 26 common frames omitted`

**Comment by Percy0601** [comment]
嗯嗯  你需要按照我说的下载当当那个dubbox  其实这里重点演示dubbo+Rest = dubbox这个示例  就是为了说明 使用rpc中间件发布rest的服务治理  从我现在的理解来看 其实没有太大必要  原因就是  内部的服务应该更轻量，dubbox的依赖第三方较多  而dubbo依赖第三方很少

**Comment by kk580kk** [comment]
大概知道问题了，需要本地zookeeper，用Multicast这个不好使，会报错上面。
