### ISSUE TITLE
运行web的时候报错

### ISSUE THREAD

**Issue by youngqiankun** [Percy0601/boot-dubbo#9]
```
2016-06-24 17:38:15.181 ERROR 42152 --- [nio-9090-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service boot.dubbo.api.UserService. Tried 3 times of the providers [192.168.31.150:20880] (1/1) from the registry 127.0.0.1:2181 on the consumer 192.168.31.150 using the dubbo version 2.8.4. Last error is: Failed to invoke remote method: sayHello, provider: dubbo://192.168.31.150:20880/boot.dubbo.api.UserService?anyhost=true&application=boot-web&check=false&dubbo=2.8.4&generic=false&interface=boot.dubbo.api.UserService&loadbalance=roundrobin&methods=sayHello,update,create,findAll&organization=ixiye&owner=yangyang&pid=42152&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1466761077781, cause: Fail to decode request due to: RpcInvocation [methodName=sayHello, parameterTypes=[], arguments=null, attachments={path=boot.dubbo.api.UserService, input=151, dubbo=2.8.4, version=0.0.0}]] with root cause

com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=sayHello, parameterTypes=[], arguments=null, attachments={path=boot.dubbo.api.UserService, input=151, dubbo=2.8.4, version=0.0.0}]
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:190)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
    at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
    at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
    at boot.dubbo.web.controller.TrainingController.hello(TrainingController.java:20)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)


```

**Comment by Percy0601** [comment]
先运行普通的 Simple 两个  然后看spring boot的

**Comment by Percy0601** [comment]
@kingyoungfan 你这马上就调通了  可以先运行dubbox自带的示例代码   然后看我是怎么排除依赖 整合spring boot的

**Comment by Percy0601** [comment]
从使用经验来看  如果不想暴露rest协议  推荐使用dubbo就可以了   更轻量

**Comment by Percy0601** [comment]
dubbo的架构非常好  但是有点大而全  有机会我想再研究一下  重构自己的dubbo  解决思路就是让核心更轻量化 性能更加强劲  dubbo的性能够用  但是想做中间件的中间件就有点慢了。。。

**Comment by youngqiankun** [comment]
我就是按照你的项目跑的，两个Simple跑起来了，web也跑起来了，zk也起来了，所有的看起来都正常

```
2016-06-24 18:18:33.817  INFO 42577 --- [ootstrap.main()] boot.dubbo.simple.ApplicationBootstrap   : Starting ApplicationBootstrap on yangyangdeMacBook-Pro.local with PID 42577 (/Users/yangyang/project/boot-dubbo/boot-dubbo-simple/target/classes started by yangyang in /Users/yangyang/project/boot-dubbo/boot-dubbo-simple)
2016-06-24 18:18:33.908  INFO 42577 --- [ootstrap.main()] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5ce10dbd: startup date [Fri Jun 24 18:18:33 CST 2016]; root of context hierarchy
2016-06-24 18:18:34.560  INFO 42577 --- [ootstrap.main()] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [META-INF/spring/applicationContext.xml]
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2016-06-24 18:18:36.382  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2016-06-24 18:18:36.383  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:host.name=192.168.31.150
2016-06-24 18:18:36.385  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.version=1.8.0_65
2016-06-24 18:18:36.398  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.vendor=Oracle Corporation
2016-06-24 18:18:36.405  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
2016-06-24 18:18:36.408  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.class.path=/usr/local/apache-maven-3.3.9/boot/plexus-classworlds-2.5.2.jar
2016-06-24 18:18:36.408  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.library.path=/Users/yangyang/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
2016-06-24 18:18:36.409  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.io.tmpdir=/var/folders/2m/rklhsjxs1vd08tq526pvjbqh0000gn/T/
2016-06-24 18:18:36.409  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.compiler=<NA>
2016-06-24 18:18:36.409  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.name=Mac OS X
2016-06-24 18:18:36.409  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.arch=x86_64
2016-06-24 18:18:36.409  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.version=10.11.5
2016-06-24 18:18:36.453  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.name=yangyang
2016-06-24 18:18:36.455  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.home=/Users/yangyang
2016-06-24 18:18:36.457  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.dir=/Users/yangyang/project/boot-dubbo/boot-dubbo-simple
2016-06-24 18:18:36.458  INFO 42577 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.I0Itec.zkclient.ZkClient@3fe88d49
2016-06-24 18:18:36.531  INFO 42577 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-06-24 18:18:36.591  INFO 42577 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
2016-06-24 18:18:36.604  INFO 42577 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x15581ea8de50001, negotiated timeout = 40000
2016-06-24 18:18:36.715  INFO 42577 --- [ootstrap.main()] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-06-24 18:18:36.753  INFO 42577 --- [ootstrap.main()] boot.dubbo.simple.ApplicationBootstrap   : Started ApplicationBootstrap in 3.299 seconds (JVM running for 9.635)

```

```

2016-06-24 18:18:53.646  INFO 42599 --- [ootstrap.main()] b.d.simple.client.ApplicationBootstrap   : Starting ApplicationBootstrap on yangyangdeMacBook-Pro.local with PID 42599 (/Users/yangyang/project/boot-dubbo/boot-dubbo-simple-client/target/classes started by yangyang in /Users/yangyang/project/boot-dubbo/boot-dubbo-simple-client)
2016-06-24 18:18:53.738  INFO 42599 --- [ootstrap.main()] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3be7ca91: startup date [Fri Jun 24 18:18:53 CST 2016]; root of context hierarchy
2016-06-24 18:18:54.306  INFO 42599 --- [ootstrap.main()] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [META-INF/spring/applicationContext.xml]
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:host.name=192.168.31.150
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.version=1.8.0_65
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.vendor=Oracle Corporation
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.class.path=/usr/local/apache-maven-3.3.9/boot/plexus-classworlds-2.5.2.jar
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.library.path=/Users/yangyang/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.io.tmpdir=/var/folders/2m/rklhsjxs1vd08tq526pvjbqh0000gn/T/
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:java.compiler=<NA>
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.name=Mac OS X
2016-06-24 18:18:55.552  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.arch=x86_64
2016-06-24 18:18:55.553  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:os.version=10.11.5
2016-06-24 18:18:55.553  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.name=yangyang
2016-06-24 18:18:55.553  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.home=/Users/yangyang
2016-06-24 18:18:55.553  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Client environment:user.dir=/Users/yangyang/project/boot-dubbo/boot-dubbo-simple-client
2016-06-24 18:18:55.554  INFO 42599 --- [ootstrap.main()] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.I0Itec.zkclient.ZkClient@6d25ac9b
2016-06-24 18:18:55.586  INFO 42599 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-06-24 18:18:55.629  INFO 42599 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
2016-06-24 18:18:55.645  INFO 42599 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x15581ea8de50002, negotiated timeout = 40000
2016-06-24 18:18:56.432  INFO 42599 --- [ootstrap.main()] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-06-24 18:18:56.442  INFO 42599 --- [ootstrap.main()] b.d.simple.client.ApplicationBootstrap   : Started ApplicationBootstrap in 3.086 seconds (JVM running for 8.146)

```

```

2016-06-24 18:20:57.002 ERROR 42630 --- [nio-9090-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service boot.dubbo.api.UserService. Tried 3 times of the providers [192.168.31.150:20880] (1/1) from the registry 127.0.0.1:2181 on the consumer 192.168.31.150 using the dubbo version 2.8.4. Last error is: Failed to invoke remote method: sayHello, provider: dubbo://192.168.31.150:20880/boot.dubbo.api.UserService?anyhost=true&application=boot-web&check=false&dubbo=2.8.4&generic=false&interface=boot.dubbo.api.UserService&loadbalance=roundrobin&methods=sayHello,update,create,findAll&organization=ixiye&owner=yangyang&pid=42630&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1466763554430, cause: Fail to decode request due to: RpcInvocation [methodName=sayHello, parameterTypes=[], arguments=null, attachments={path=boot.dubbo.api.UserService, input=151, dubbo=2.8.4, version=0.0.0}]] with root cause

com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=sayHello, parameterTypes=[], arguments=null, attachments={path=boot.dubbo.api.UserService, input=151, dubbo=2.8.4, version=0.0.0}]
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:190)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
    at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
    at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
    at boot.dubbo.web.controller.TrainingController.hello(TrainingController.java:20)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)


```

**Comment by youngqiankun** [comment]
是不是缺少解码的jar包？？？

**Comment by Percy0601** [comment]
@kingyoungfan 协议不对  序列化协议不对  肯定一个配置了json  一个不支持json rest类似的问题  自己解决一下吧  小问题不在显示器旁边帮不了你

**Comment by Percy0601** [comment]
建议你先学习  我写的参考示例：https://github.com/Percy0601/training-rmi

先学习rmi  懂了这个 dubbo不是问题  很简单的

**Comment by youngqiankun** [comment]
确实像您说的这样，谢谢！，自己还是有很多东西要学！再次感谢
